#pragma once
#include <GLFW/glfw3.h>

using KeyCode = uint16_t;
namespace Pixie::Inputs
{
/* NOTES COPPIED FROM GLFW3.H
*  ... Keyboard key tokens.
*
*  See [key input](@ref input_key) for how these are used.
*
*  These key codes are inspired by the _USB HID Usage Tables v1.12_ (p. 53-60),
*  but re-arranged to map to 7-bit ASCII for printable keys (function keys are
*  put in the 256+ range).
*
*  The naming of the key codes follow these rules:
*   - The US keyboard layout is used
*   - Names of printable alphanumeric characters are used (e.g. "A", "R",
*     "3", etc.)
*   - For non-alphanumeric characters, Unicode:ish names are used (e.g.
*     "COMMA", "LEFT_SQUARE_BRACKET", etc.). Note that some names do not
*     correspond to the Unicode standard (usually for brevity)
*   - Keys that lack a clear US mapping are named "WORLD_x"
*   - For non-printable keys, custom names are used (e.g. "F4",
*     "BACKSPACE", etc.)
*/
	enum class Keyboard : KeyCode
	{
		/* Printable keys */
		Space = GLFW_KEY_SPACE,
		Apostrophe = GLFW_KEY_APOSTROPHE,
		Comma = GLFW_KEY_COMMA,
		Dash = GLFW_KEY_MINUS,
		Period = GLFW_KEY_PERIOD,
		Slash = GLFW_KEY_SLASH,
		Zero = GLFW_KEY_0,
		One = GLFW_KEY_1,
		Two = GLFW_KEY_2,
		Three = GLFW_KEY_3,
		Four = GLFW_KEY_4,
		Five = GLFW_KEY_5,
		Six = GLFW_KEY_6,
		Seven = GLFW_KEY_7,
		Eight = GLFW_KEY_8,
		Nine = GLFW_KEY_9,
		Semicolon = GLFW_KEY_SEMICOLON,
		Equal = GLFW_KEY_EQUAL,
		A = GLFW_KEY_A,
		B = GLFW_KEY_B,
		C = GLFW_KEY_C,
		D = GLFW_KEY_D,
		E = GLFW_KEY_E,
		F = GLFW_KEY_F,
		G = GLFW_KEY_G,
		H = GLFW_KEY_H,
		I = GLFW_KEY_I,
		J = GLFW_KEY_J,
		K = GLFW_KEY_K,
		L = GLFW_KEY_L,
		M = GLFW_KEY_M,
		N = GLFW_KEY_N,
		O = GLFW_KEY_O,
		P = GLFW_KEY_P,
		Q = GLFW_KEY_Q,
		R = GLFW_KEY_R,
		S = GLFW_KEY_S,
		T = GLFW_KEY_T,
		U = GLFW_KEY_U,
		V = GLFW_KEY_V,
		W = GLFW_KEY_W,
		X = GLFW_KEY_X,
		Y = GLFW_KEY_Y,
		Z = GLFW_KEY_Z,
		LeftBracket = GLFW_KEY_LEFT_BRACKET,
		Backslash = GLFW_KEY_BACKSLASH,
		RightBracket = GLFW_KEY_RIGHT_BRACKET,
		Accent = GLFW_KEY_GRAVE_ACCENT,
		World1 = GLFW_KEY_WORLD_1,
		World2 = GLFW_KEY_WORLD_2,
		/* Function keys */
		Escape = GLFW_KEY_ESCAPE,
		Enter = GLFW_KEY_ENTER,
		Tab = GLFW_KEY_TAB,
		Backspace = GLFW_KEY_BACKSPACE,
		Insert = GLFW_KEY_INSERT,
		Delete = GLFW_KEY_DELETE,
		Right = GLFW_KEY_RIGHT,
		Left = GLFW_KEY_LEFT,
		Down = GLFW_KEY_DOWN,
		Up = GLFW_KEY_UP,
		PageUp = GLFW_KEY_PAGE_UP,
		PageDown = GLFW_KEY_PAGE_DOWN,
		Home = GLFW_KEY_HOME,
		End = GLFW_KEY_END,
		CapsLock = GLFW_KEY_CAPS_LOCK,
		ScrollLock= GLFW_KEY_SCROLL_LOCK,
		NumLock = GLFW_KEY_NUM_LOCK,
		Print = GLFW_KEY_PRINT_SCREEN,
		Pause = GLFW_KEY_PAUSE,
		F1 = GLFW_KEY_F1,
		F2 = GLFW_KEY_F2,
		F3 = GLFW_KEY_F3,
		F4 = GLFW_KEY_F4,
		F5 = GLFW_KEY_F5,
		F6 = GLFW_KEY_F6,
		F7 = GLFW_KEY_F7,
		F8 = GLFW_KEY_F8,
		F9 = GLFW_KEY_F9,
		F10 = GLFW_KEY_F10,
		F11 = GLFW_KEY_F11,
		F12 = GLFW_KEY_F12,
		F13 = GLFW_KEY_F13,
		F14 = GLFW_KEY_F14,
		F15 = GLFW_KEY_F15,
		F16 = GLFW_KEY_F16,
		F17 = GLFW_KEY_F17,
		F18 = GLFW_KEY_F18,
		F19 = GLFW_KEY_F19,
		F20 = GLFW_KEY_F20,
		F21 = GLFW_KEY_F21,
		F22 = GLFW_KEY_F22,
		F23 = GLFW_KEY_F23,
		F24 = GLFW_KEY_F24,
		F25 = GLFW_KEY_F25,
		KP_0 = GLFW_KEY_KP_0,
		KP_1 = GLFW_KEY_KP_1,
		KP_2 = GLFW_KEY_KP_2,
		KP_3 = GLFW_KEY_KP_3,
		KP_4 = GLFW_KEY_KP_4,
		KP_5 = GLFW_KEY_KP_5,
		KP_6 = GLFW_KEY_KP_6,
		KP_7 = GLFW_KEY_KP_7,
		KP_8 = GLFW_KEY_KP_8,
		KP_9 = GLFW_KEY_KP_9,
		KP_Decimal = GLFW_KEY_KP_DECIMAL,
		KP_Divide = GLFW_KEY_KP_DIVIDE,
		KP_Multiply = GLFW_KEY_KP_MULTIPLY,
		KP_Subtract = GLFW_KEY_KP_SUBTRACT,
		KP_Add = GLFW_KEY_KP_ADD,
		KP_Enter = GLFW_KEY_KP_ENTER,
		KP_Equal = GLFW_KEY_KP_EQUAL,
		LeftShift = GLFW_KEY_LEFT_SHIFT,
		LeftControl = GLFW_KEY_LEFT_CONTROL,
		LeftAlt = GLFW_KEY_LEFT_ALT,
		LeftSuper = GLFW_KEY_LEFT_SUPER,
		RightShift = GLFW_KEY_RIGHT_SHIFT,
		RightControl = GLFW_KEY_RIGHT_CONTROL,
		RightAlt= GLFW_KEY_RIGHT_ALT,
		RightSuper = GLFW_KEY_RIGHT_SUPER,
		Menu = GLFW_KEY_MENU,
	};


    const std::unordered_map<Keyboard, std::string> KeyboardNames{
   // {Keyboard::UNKNOWN, "unknown"},
    {Keyboard::Space, "Spacebar"},
    {Keyboard::Apostrophe, "Apostrophe"},
    {Keyboard::Comma, "Comma"},
    {Keyboard::Dash, "Dash"},
    {Keyboard::Period, "Period"},
    {Keyboard::Slash, "Slash"},
    {Keyboard::Zero, "0"},
    {Keyboard::One, "1"},
    {Keyboard::Two, "2"},
    {Keyboard::Three, "3"},
    {Keyboard::Four, "4"},
    {Keyboard::Five, "5"},
    {Keyboard::Six, "6"},
    {Keyboard::Seven, "7"},
    {Keyboard::Eight, "8"},
    {Keyboard::Nine, "9"},
    {Keyboard::Semicolon, "Semicolon"},
    {Keyboard::Equal, "Equal Sign"},
    {Keyboard::A, "a"},
    {Keyboard::B, "b"},
    {Keyboard::C, "c"},
    {Keyboard::D, "d"},
    {Keyboard::E, "e"},
    {Keyboard::F, "f"},
    {Keyboard::G, "g"},
    {Keyboard::H, "h"},
    {Keyboard::I, "i"},
    {Keyboard::J, "j"},
    {Keyboard::K, "k"},
    {Keyboard::L, "l"},
    {Keyboard::M, "m"},
    {Keyboard::N, "n"},
    {Keyboard::O, "o"},
    {Keyboard::P, "p"},
    {Keyboard::Q, "q"},
    {Keyboard::R, "r"},
    {Keyboard::S, "s"},
    {Keyboard::T, "t"},
    {Keyboard::U, "u"},
    {Keyboard::V, "v"},
    {Keyboard::W, "w"},
    {Keyboard::X, "x"},
    {Keyboard::Y, "y"},
    {Keyboard::Z, "z"},
    {Keyboard::LeftBracket, "Left Bracket"},
    {Keyboard::Backslash, "Backslash"},
    {Keyboard::RightBracket, "Right Bracket"},
    {Keyboard::Accent, "Accent"},
    {Keyboard::World1, "World 1"},
    {Keyboard::World2, "World 2"},
    {Keyboard::Escape, "Escape"},
    {Keyboard::Enter, "Enter"},
    {Keyboard::Tab, "    "},
    {Keyboard::Backspace, "Backspace"},
    {Keyboard::Insert, "Insert"},
    {Keyboard::Delete, "Delete"},
    {Keyboard::Right, "Right Arrow"},
    {Keyboard::Left, "Left Arrow"},
    {Keyboard::Down, "Down Arrow"},
    {Keyboard::Up, "Up Arrow"},
    {Keyboard::PageUp, "Page Up"},
    {Keyboard::PageDown, "Page Down"},
    {Keyboard::Home, "Home"},
    {Keyboard::End, "End"},
    {Keyboard::CapsLock, "Caps Lock"},
    {Keyboard::ScrollLock, "Scroll Lock"},
    {Keyboard::NumLock, "Num Lock"},
    {Keyboard::Print, "Print Screen"},
    {Keyboard::Pause, "Pause"},
    {Keyboard::F1, "f1"},
    {Keyboard::F2, "f2"},
    {Keyboard::F3, "f3"},
    {Keyboard::F4, "f4"},
    {Keyboard::F5, "f5"},
    {Keyboard::F6, "f6"},
    {Keyboard::F7, "f7"},
    {Keyboard::F8, "f8"},
    {Keyboard::F9, "f9"},
    {Keyboard::F10, "f10"},
    {Keyboard::F11, "f11"},
    {Keyboard::F12, "f12"},
    {Keyboard::F13, "f13"},
    {Keyboard::F14, "f14"},
    {Keyboard::F15, "f15"},
    {Keyboard::F16, "f16"},
    {Keyboard::F17, "f17"},
    {Keyboard::F18, "f18"},
    {Keyboard::F19, "f19"},
    {Keyboard::F20, "f20"},
    {Keyboard::F21, "f21"},
    {Keyboard::F22, "f22"},
    {Keyboard::F23, "f23"},
    {Keyboard::F24, "f24"},
    {Keyboard::F25, "f25"},
    {Keyboard::KP_0, "Keypad 0"},
    {Keyboard::KP_1, "Keypad 1"},
    {Keyboard::KP_2, "Keypad 2"},
    {Keyboard::KP_3, "Keypad 3"},
    {Keyboard::KP_4, "Keypad 4"},
    {Keyboard::KP_5, "Keypad 5"},
    {Keyboard::KP_6, "Keypad 6"},
    {Keyboard::KP_7, "Keypad 7"},
    {Keyboard::KP_8, "Keypad 8"},
    {Keyboard::KP_9, "Keypad 9"},
    {Keyboard::KP_Decimal, "Keypad Decimal"},
    {Keyboard::KP_Divide, "Keypad  Divide"},
    {Keyboard::KP_Multiply, "Keypad Multiply"},
    {Keyboard::KP_Subtract, "Keypad Subtract"},
    {Keyboard::KP_Add, "Keypad Add"},
    {Keyboard::KP_Enter, "Keypad Enter"},
    {Keyboard::KP_Equal, "Keypad Equal"},
    {Keyboard::LeftShift, "Left Shift"},
    {Keyboard::LeftControl, "Left Control"},
    {Keyboard::LeftAlt, "Left Alt"},
    {Keyboard::LeftSuper, "Left Super"},
    {Keyboard::RightShift, "Right Shift"},
    {Keyboard::RightControl, "Right Control"},
    {Keyboard::RightAlt, "Right Alt"},
    {Keyboard::RightSuper, "Right Super"},
    {Keyboard::Menu, "Menu"}
    };

    const std::unordered_map<Keyboard, std::string> KeboardToTypingString{
         {Keyboard::Space, " "},
         {Keyboard::Apostrophe, "'"},
         {Keyboard::Comma, ","},
         {Keyboard::Dash, "-"},
         {Keyboard::Period, "."},
         {Keyboard::Slash, "/"},
         {Keyboard::Zero, "0"},
         {Keyboard::One, "1"},
         {Keyboard::Two, "2"},
         {Keyboard::Three, "3"},
         {Keyboard::Four, "4"},
         {Keyboard::Five, "5"},
         {Keyboard::Six, "6"},
         {Keyboard::Seven, "7"},
         {Keyboard::Eight, "8"},
         {Keyboard::Nine, "9"},
         {Keyboard::Semicolon, ";"},
         {Keyboard::Equal, "="},
         {Keyboard::A, "a"},
         {Keyboard::B, "b"},
         {Keyboard::C, "c"},
         {Keyboard::D, "d"},
         {Keyboard::E, "e"},
         {Keyboard::F, "f"},
         {Keyboard::G, "g"},
         {Keyboard::H, "h"},
         {Keyboard::I, "i"},
         {Keyboard::J, "j"},
         {Keyboard::K, "k"},
         {Keyboard::L, "l"},
         {Keyboard::M, "m"},
         {Keyboard::N, "n"},
         {Keyboard::O, "o"},
         {Keyboard::P, "p"},
         {Keyboard::Q, "q"},
         {Keyboard::R, "r"},
         {Keyboard::S, "s"},
         {Keyboard::T, "t"},
         {Keyboard::U, "u"},
         {Keyboard::V, "v"},
         {Keyboard::W, "w"},
         {Keyboard::X, "x"},
         {Keyboard::Y, "y"},
         {Keyboard::Z, "z"},
         {Keyboard::LeftBracket, "{"},
         {Keyboard::Backslash, "\\"},
         {Keyboard::RightBracket, "}"},
         {Keyboard::Accent, "`"},
         {Keyboard::Tab, "    "},
        
         {Keyboard::KP_0, "0"},
         {Keyboard::KP_1, "1"},
         {Keyboard::KP_2, "2"},
         {Keyboard::KP_3, "3"},
         {Keyboard::KP_4, "4"},
         {Keyboard::KP_5, "5"},
         {Keyboard::KP_6, "6"},
         {Keyboard::KP_7, "7"},
         {Keyboard::KP_8, "8"},
         {Keyboard::KP_9, "9"},
         {Keyboard::KP_Decimal, "."},
         {Keyboard::KP_Divide, "/"},
         {Keyboard::KP_Multiply, "*"},
         {Keyboard::KP_Subtract, "-"},
         {Keyboard::KP_Add, "+"},
         {Keyboard::KP_Equal, "="},
    };
}